// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDomkOuIyjb1yhP3CtIaz2wg7E-3Wt8KWE',
    appId: '1:374502387395:web:094bb814f255f7a0adbc76',
    messagingSenderId: '374502387395',
    projectId: 'tst-psh-prjct',
    authDomain: 'tst-psh-prjct.firebaseapp.com',
    storageBucket: 'tst-psh-prjct.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWOCbHatJZ4V9ghoEdghTwhj-m6A9BF78',
    appId: '1:374502387395:android:9168f7a21f2ff5d2adbc76',
    messagingSenderId: '374502387395',
    projectId: 'tst-psh-prjct',
    storageBucket: 'tst-psh-prjct.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMWkO4cxAh5NC6mVKDy0TFHyJURLW1qgY',
    appId: '1:374502387395:ios:fbb1626c49402793adbc76',
    messagingSenderId: '374502387395',
    projectId: 'tst-psh-prjct',
    storageBucket: 'tst-psh-prjct.appspot.com',
    iosBundleId: 'com.example.pushTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMWkO4cxAh5NC6mVKDy0TFHyJURLW1qgY',
    appId: '1:374502387395:ios:fbb1626c49402793adbc76',
    messagingSenderId: '374502387395',
    projectId: 'tst-psh-prjct',
    storageBucket: 'tst-psh-prjct.appspot.com',
    iosBundleId: 'com.example.pushTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDomkOuIyjb1yhP3CtIaz2wg7E-3Wt8KWE',
    appId: '1:374502387395:web:a70c1ea2818330a1adbc76',
    messagingSenderId: '374502387395',
    projectId: 'tst-psh-prjct',
    authDomain: 'tst-psh-prjct.firebaseapp.com',
    storageBucket: 'tst-psh-prjct.appspot.com',
  );
}
